#!/bin/sh
set -euo pipefail

# get the version tag from saku.md
VERSION=$(sed -e 's/^.*saku  *v\([0-9]*\.[0-9]*\.[0-9]\).*$/\1/p;d' < saku.md)
TAG=v$VERSION
VERSION_DIR=$HOME/.saku/$TAG
EXE=$VERSION_DIR/saku

# Download it if the binary doesn't exist.
if [ ! -e "$EXE" ]; then
  echo "Downloading the binary"
  TEMP=$(mktemp)
  curl -L https://github.com/kt3k/saku/releases/download/$TAG/saku_${VERSION}_$(uname | tr '[:upper:]' '[:lower:]')_amd64.tar.gz -o $TEMP/bin.tgz # download
  echo "Extracting the binary"
  mkdir -p $VERSION_DIR
  # gunzip ...
  rm -rf $TEMP
  chmod +x $EXE
fi

# Run saku
$EXE $@
